table Tabla
	lineageTag: 41a8088e-4357-40f4-9675-788d9c49f20a

	measure Medida = MAX(Tabla[Col1])
		formatString: 0
		lineageTag: e2e403fd-7650-4215-8538-1e1dda7bfb37

	measure 'Medida 2' = MIN(Tabla[Col2])
		lineageTag: de79b85b-8695-4ee3-92a0-e9e79ed72ae8

	column Col1
		dataType: int64
		formatString: 0
		lineageTag: 21008b0d-0624-43bf-b63a-8c8255744bdc
		summarizeBy: sum
		sourceColumn: Col1

		annotation SummarizationSetBy = Automatic

	column Col2
		dataType: string
		lineageTag: 08060ed6-af9f-4a94-8576-cfdf5f9b3fe3
		summarizeBy: none
		sourceColumn: Col2

		annotation SummarizationSetBy = Automatic

	partition Tabla = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUUpUitWJVjICspLALGMgK1kpNhYA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Col1 = _t, Col2 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Col1", Int64.Type}, {"Col2", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

